package provider

import (
	"context"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/Prideth/terraform-provider-sap-integration-suite/internal/client/cloudintegration"
	v2 "github.com/Prideth/terraform-provider-sap-integration-suite/internal/client/odata/v2"
)

// NewServiceEndpointsDataSource returns a fresh datasource.DataSource
// implementation for sapintegrationsuite_service_endpoints.
func NewServiceEndpointsDataSource() datasource.DataSource {
	return &serviceEndpointsDataSource{}
}

type serviceEndpointsDataSource struct {
	client *cloudintegration.Client
}

type serviceEndpointsDataSourceModel struct {
	Name      types.String               `tfsdk:"name"`
	Protocol  types.String               `tfsdk:"protocol"`
	Endpoints []serviceEndpointListEntry `tfsdk:"endpoints"`
}

type serviceEndpointListEntry struct {
	ID             types.String         `tfsdk:"id"`
	Name           types.String         `tfsdk:"name"`
	Title          types.String         `tfsdk:"title"`
	Version        types.String         `tfsdk:"version"`
	Summary        types.String         `tfsdk:"summary"`
	Description    types.String         `tfsdk:"description"`
	LastUpdated    types.String         `tfsdk:"last_updated"`
	Protocol       types.String         `tfsdk:"protocol"`
	EntryPoints    []entryPointEntry    `tfsdk:"entry_points"`
	APIDefinitions []apiDefinitionEntry `tfsdk:"api_definitions"`
}

type entryPointEntry struct {
	Name                  types.String `tfsdk:"name"`
	URL                   types.String `tfsdk:"url"`
	Type                  types.String `tfsdk:"type"`
	AdditionalInformation types.String `tfsdk:"additional_information"`
}

type apiDefinitionEntry struct {
	URL  types.String `tfsdk:"url"`
	Name types.String `tfsdk:"name"`
}

func (d *serviceEndpointsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_service_endpoints"
}

func (d *serviceEndpointsDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Discovers the runtime service endpoints SAP exposes for deployed Cloud " +
			"Integration content (the public ServiceEndpoints OData V2 API). This is discovery " +
			"only: service endpoints are generated by SAP the moment matching content is deployed " +
			"and disappear when it is undeployed, so there is no corresponding Terraform resource " +
			"— the desired state that produces an endpoint lives in " +
			"sapintegrationsuite_integration_flow / sapintegrationsuite_integration_flow_deployment " +
			"(or the equivalent for other artifact types). This data source never invokes a " +
			"discovered endpoint URL, downloads a referenced API definition document, or changes " +
			"any runtime state; it only reads metadata. name and protocol are optional filters " +
			"applied server-side via SAP's documented `Name eq '...'`/`Protocol eq '...'` OData " +
			"$filter; leaving both unset returns every visible service endpoint. Every page SAP " +
			"returns is fetched, and the result is sorted deterministically (by name, then " +
			"protocol, with each endpoint's entry_points/api_definitions sorted too), since SAP " +
			"does not document a guaranteed response order. See docs/guides/service-endpoints.md.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Optional: true,
				Description: "Only return service endpoints for the integration artifact with this " +
					"exact name (SAP's documented `Name eq '...'` filter).",
			},
			"protocol": schema.StringAttribute{
				Optional: true,
				Description: "Only return service endpoints with this exact protocol, as SAP " +
					"reports it (for example \"SOAP\", \"ODATAV2\", \"AS2\", \"AS4\", \"REST\" — " +
					"SAP's documented `Protocol eq '...'` filter). This provider does not reverse-" +
					"map protocol values to adapter types; it exposes exactly what SAP returns.",
			},
			"endpoints": schema.ListNestedAttribute{
				Computed:    true,
				Description: "Every service endpoint matching the optional name/protocol filters.",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:    true,
							Description: "SAP's identifier of the service endpoint.",
						},
						"name": schema.StringAttribute{
							Computed:    true,
							Description: "The integration artifact's name this endpoint belongs to.",
						},
						"title": schema.StringAttribute{
							Computed:    true,
							Description: "Display title, when SAP reports one.",
						},
						"version": schema.StringAttribute{
							Computed:    true,
							Description: "Version of the deployed artifact behind the endpoint, when SAP reports one.",
						},
						"summary": schema.StringAttribute{
							Computed:    true,
							Description: "Short summary, when SAP reports one.",
						},
						"description": schema.StringAttribute{
							Computed:    true,
							Description: "Description, when SAP reports one.",
						},
						"last_updated": schema.StringAttribute{
							Computed: true,
							Description: "When SAP last updated the endpoint, as an RFC 3339 timestamp in UTC. If SAP " +
								"returns a value that is not an OData V2 date literal, it is passed through unchanged.",
						},
						"protocol": schema.StringAttribute{
							Computed:    true,
							Description: "The endpoint's protocol, exactly as SAP returns it.",
						},
						"entry_points": schema.ListNestedAttribute{
							Computed: true,
							Description: "Runtime URLs exposed for this endpoint. SAP documents " +
								"entry point Name/url as required and type as optional.",
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"name": schema.StringAttribute{
										Computed:    true,
										Description: "The entry point's name.",
									},
									"url": schema.StringAttribute{
										Computed:    true,
										Description: "The fully qualified entry point URL or base path.",
									},
									"type": schema.StringAttribute{
										Computed: true,
										Description: "The entry point's environment, when SAP " +
											"reports one: \"DEV\", \"TEST\", \"PROD\", or " +
											"\"SANDBOX\".",
									},
									"additional_information": schema.StringAttribute{
										Computed:    true,
										Description: "Additional information SAP attaches to the entry point, when present.",
									},
								},
							},
						},
						"api_definitions": schema.ListNestedAttribute{
							Computed: true,
							Description: "Links to machine-readable API definition documents for " +
								"this endpoint (OpenAPI, EDMX, WSDL, and similar). This provider " +
								"never downloads the document at url — only the link itself is " +
								"returned.",
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"url": schema.StringAttribute{
										Computed:    true,
										Description: "The fully qualified URL to the API definition document.",
									},
									"name": schema.StringAttribute{
										Computed: true,
										Description: "Name SAP gives the definition link. Earlier releases exposed a " +
											"\"type\" here, which the API does not have and which was always empty.",
									},
								},
							},
						},
					},
				},
			},
		},
	}
}

func (d *serviceEndpointsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	data, ok := req.ProviderData.(*Data)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data type", "Expected *provider.Data")
		return
	}
	if !requireHTTPClient(data, "data source", &resp.Diagnostics) {
		return
	}
	d.client = cloudintegration.New(data.HTTPClient, data.Host)
}

func (d *serviceEndpointsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config serviceEndpointsDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	endpoints, err := d.client.ListServiceEndpoints(ctx, config.Name.ValueString(), config.Protocol.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Failed to list SAP Integration Suite service endpoints", diagnosticDetail(err))
		return
	}

	values := make([]serviceEndpointListEntry, 0, len(endpoints))
	for _, e := range endpoints {
		values = append(values, serviceEndpointListEntry{
			ID:             stringOrNull(e.ID),
			Name:           types.StringValue(e.Name),
			Title:          stringOrNull(e.Title),
			Version:        stringOrNull(e.Version),
			Summary:        stringOrNull(e.Summary),
			Description:    stringOrNull(e.Description),
			LastUpdated:    odataDateToRFC3339(e.LastUpdated),
			Protocol:       types.StringValue(e.Protocol),
			EntryPoints:    entryPointsToModel(e.EntryPoints.Results),
			APIDefinitions: apiDefinitionsToModel(e.APIDefinitions.Results),
		})
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, serviceEndpointsDataSourceModel{
		Name:      config.Name,
		Protocol:  config.Protocol,
		Endpoints: values,
	})...)
}

func entryPointsToModel(entries []cloudintegration.EntryPoint) []entryPointEntry {
	values := make([]entryPointEntry, 0, len(entries))
	for _, ep := range entries {
		values = append(values, entryPointEntry{
			Name:                  types.StringValue(ep.Name),
			URL:                   types.StringValue(ep.URL),
			Type:                  stringOrNull(ep.Type),
			AdditionalInformation: stringOrNull(ep.AdditionalInformation),
		})
	}
	return values
}

func apiDefinitionsToModel(defs []cloudintegration.APIDefinition) []apiDefinitionEntry {
	values := make([]apiDefinitionEntry, 0, len(defs))
	for _, def := range defs {
		values = append(values, apiDefinitionEntry{
			URL:  types.StringValue(def.URL),
			Name: stringOrNull(def.Name),
		})
	}
	return values
}

// odataDateToRFC3339 converts an OData V2 "/Date(<millis>)/" literal to
// RFC 3339. Anything else is passed through unchanged rather than dropped.
func odataDateToRFC3339(s string) types.String {
	if s == "" {
		return types.StringNull()
	}
	t, err := v2.ParseDateLiteral(s)
	if err != nil {
		return types.StringValue(s)
	}
	return types.StringValue(t.Format(time.RFC3339))
}
